<%@ Page Title="" Language="C#" MasterPageFile="~/admin/adminMaster.Master" AutoEventWireup="true" CodeBehind="Admin.aspx.cs" Inherits="kstarbox.admin.Admins" %>
<script runat="server">
    private void datagridupdate(Object source, SqlDataSourceStatusEventArgs d)
    {
        if(d.AffectedRows > 0)
        {
            insmsg.Text = "Update success";
        }
        else
        {
            insmsg.Text = "No data updated!";
        }
    }
</script>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder2" runat="server">
    <div class="addProdHeader"><h3>Add Product</h3></div>
        <div class="addFormWrapper">
            
                <div class="reglabel"><asp:Label runat="server" ID="pnamelbl" Text="Product Name:" AssociatedControlID="pnametbox"></asp:Label></div>
                <div class="regtxtbox"><asp:TextBox ID="pnametbox" runat="server" Text='<%# Bind("prod_name") %>' Width="250px" /></div>
               
                <div class="reglabel"><asp:Label runat="server" ID="pdetslbl" Text=" Product Details:" AssociatedControlID="pdetstxtbox"></asp:Label></div>
               <div class="regtxtbox"><asp:TextBox ID="pdetstxtbox" runat="server" Text='<%# Bind("prod_details") %>' TextMode="MultiLine" Width="250px" /></div> 
                
                <div class="reglabel"><asp:Label runat="server" ID="pricelbl" Text="Product Price (BND):" AssociatedControlID="pricetxt"></asp:Label></div>
                <div class="regtxtbox"><asp:TextBox ID="pricetxt" runat="server" Text='<%# Bind("prod_price") %>' Width="250px" /></div>
               
                <div class="reglabel"><asp:Label runat="server" ID="pqtylbl" Text="Product Quantity:" AssociatedControlID="pqtytxt"></asp:Label></div>
                <div class="regtxtbox"><asp:TextBox ID="pqtytxt" runat="server" Text='<%# Bind("prod_quantity") %>' Width="250px" /></div>
                    <div class="regbuttoncss"><asp:Button ID="Button2" runat="server" Text="Add" OnClick="Button2_Click" /></div>
                    <div class="lit"><asp:Literal ID="insmsg" runat="server"></asp:Literal></div>
            </div>
        <div class="manageProdHeader"><h3>Manage Product</h3></div>
        <div class="datagridAdminWrapper">
            
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            
            <asp:GridView ID="prodgrid" runat="server" AutoGenerateColumns="False" DataKeyNames="id" DataSourceID="adminDS" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True">
                <Columns>
                    <asp:BoundField DataField="id" HeaderText="ID" InsertVisible="False" ReadOnly="True" SortExpression="id" />
                    <asp:BoundField DataField="prod_name" HeaderText="Name" SortExpression="prod_name" />
                    <asp:BoundField DataField="prod_details" HeaderText="Product details" SortExpression="prod_details" />
                    <asp:BoundField DataField="prod_price" HeaderText="Price" SortExpression="prod_price" />
                    <asp:BoundField DataField="prod_quantity" HeaderText="Current quantity" SortExpression="prod_quantity" />
                    <asp:BoundField DataField="onFeatured" HeaderText="Place on featured (yes/no)" SortExpression="onFeatured" />
                    <asp:HyperLinkField DataNavigateUrlFields="prod_name" DataNavigateUrlFormatString="img_upload.aspx?prod_name={0}" HeaderText="Image" Text="Upload" />
                </Columns>
                <RowStyle CssClass="prodgridtable" />
            </asp:GridView>
            <asp:SqlDataSource ID="adminDS" runat="server" ConnectionString="<%$ ConnectionStrings:db_1624956_kstardbGrid %>" 
                OldValuesParameterFormatString="original_{0}" SelectCommand="SELECT * FROM [prod_table]" 
                UpdateCommand="UPDATE [prod_table] SET [prod_name] = @prod_name, [prod_details] = @prod_details, [prod_price] = @prod_price, [prod_quantity] = @prod_quantity, [onFeatured] = @onFeatured WHERE [id] = @original_id"
          OnUpdated="datagridupdate" 
                DeleteCommand="DELETE FROM [prod_table] WHERE [id] = @original_id" InsertCommand="INSERT INTO [prod_table] ([prod_name], [prod_details], [prod_price], [prod_quantity], [onFeatured]) VALUES (@prod_name, @prod_details, @prod_price, @prod_quantity, @onFeatured)">
                <DeleteParameters>
                    <asp:Parameter Name="original_id" Type="Int32" />
                </DeleteParameters>
                <InsertParameters>
                    <asp:Parameter Name="prod_name" Type="String" />
                    <asp:Parameter Name="prod_details" Type="String" />
                    <asp:Parameter Name="prod_price" Type="String" />
                    <asp:Parameter Name="prod_quantity" Type="Int32" />
                    <asp:Parameter Name="onFeatured" Type="String" />
                </InsertParameters>
                <UpdateParameters>
                    <asp:Parameter Name="prod_name" Type="String" />
                    <asp:Parameter Name="prod_details" Type="String" />
                    <asp:Parameter Name="prod_price" Type="String" />
                    <asp:Parameter Name="prod_quantity" Type="Int32" />
                    <asp:Parameter Name="onFeatured" Type="String" />
                    <asp:Parameter Name="original_id" Type="Int32" />
                </UpdateParameters>
            </asp:SqlDataSource>
        </div>
        </asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    <asp:Button ID="signoutbut" runat="server" Text="Sign out" OnClick="signoutbut_Click" OnClientClick="window.open('../Default.aspx', 'Default')" Font-Bold="True" Font-Size="Medium" />
</asp:Content>
