<%@ Page Title="" Language="C#" MasterPageFile="~/admin/adminMaster.Master" AutoEventWireup="true" CodeBehind="img_upload.aspx.cs" Inherits="kstarbox.Itempage" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="ContentPlaceHolder2" runat="server">
    <div class="imguploadheader"><asp:Label ID="Label8" runat="server" Text="Main Image"></asp:Label></div>
    <div class="upimgwrap">
    <div class="imguploadmargin"><asp:Image ID="imgselect" runat="server" Width="300px" Height="300px"/></div>
    <div class="regbuttoncss"><asp:Button ID="shwimg" runat="server" OnClick="shwimg_Click" Text="show current product image" /><asp:Button ID="Button3" runat="server" OnClick="Button3_Click" Text="Hide image" /></div>
    <div class="lit"><asp:Literal ID="showimglit" runat="server"></asp:Literal></div>
    <div class="loglabel"><asp:Label ID="Label4" runat="server" Text="First image upload (Big / main image)"></asp:Label></div>
    <div class="loglabel"><asp:FileUpload ID="selectimg" runat="server" /></div>
    <div class="loglabel"><asp:Label ID="Label1" runat="server" Text="Alternate text: " AssociatedControlID="setalttxt"></asp:Label><asp:TextBox ID="setalttxt" runat="server"></asp:TextBox></div>
    <div class="loginbutton"><asp:Button ID="cfm_img_upload" runat="server" OnClick="cfm_img_upload_Click" Text="Confirm" /></div>
    
    <div><asp:Literal ID="img_uploadLit" runat="server"></asp:Literal></div>
    
    <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" DataKeyNames="imageID" DataSourceID="previmg">
        <Columns>
            <asp:BoundField DataField="imageID" HeaderText="Image ID" InsertVisible="False" ReadOnly="True" SortExpression="imageID" />
            <asp:BoundField DataField="width" HeaderText="Image width" SortExpression="width" />
            <asp:BoundField DataField="height" HeaderText="Image height" SortExpression="height" />
            <asp:BoundField DataField="altText" HeaderText="Alternate text" SortExpression="altText" />
            <asp:BoundField DataField="extension" HeaderText="Image type" SortExpression="extension" />
            <asp:BoundField DataField="imgName" HeaderText="Image name" SortExpression="imgName" />
        </Columns>
    </asp:GridView>
        
        <asp:SqlDataSource ID="previmg" runat="server" ConnectionString="<%$ ConnectionStrings:db_1624956_kstardbprevimg %>" SelectCommand="SELECT * FROM [image_table] WHERE ([imgName] = @imgName)" DeleteCommand="DELETE FROM [image_table] WHERE [imageID] = @imageID" InsertCommand="INSERT INTO [image_table] ([width], [height], [altText], [extension], [imgName]) VALUES (@width, @height, @altText, @extension, @imgName)" UpdateCommand="UPDATE [image_table] SET [width] = @width, [height] = @height, [altText] = @altText, [extension] = @extension, [imgName] = @imgName WHERE [imageID] = @imageID">
            <DeleteParameters>
                <asp:Parameter Name="imageID" Type="Int32" />
            </DeleteParameters>
            <InsertParameters>
                <asp:Parameter Name="width" Type="Int32" />
                <asp:Parameter Name="height" Type="Int32" />
                <asp:Parameter Name="altText" Type="String" />
                <asp:Parameter Name="extension" Type="String" />
                <asp:Parameter Name="imgName" Type="String" />
            </InsertParameters>
            <SelectParameters>
                <asp:QueryStringParameter DefaultValue="" Name="imgName" QueryStringField="prod_name" Type="String" />
            </SelectParameters>
            <UpdateParameters>
                <asp:Parameter Name="width" Type="Int32" />
                <asp:Parameter Name="height" Type="Int32" />
                <asp:Parameter Name="altText" Type="String" />
                <asp:Parameter Name="extension" Type="String" />
                <asp:Parameter Name="imgName" Type="String" />
                <asp:Parameter Name="imageID" Type="Int32" />
            </UpdateParameters>
        </asp:SqlDataSource>
        
        </div>
    <div class="imguploadheader"><asp:Label ID="Label7" runat="server" Text="2nd preview Image"></asp:Label></div>
    <div class="upimgwrap">
    <div class="imguploadmargin"><asp:Image ID="Image1" runat="server" Width="300px" Height="300px" /></div>
    <div class="regbuttoncss"><asp:Button ID="Button1" runat="server" OnClick="Button1_Click" Text="Show current image" /><asp:Button ID="Button4" runat="server" OnClick="Button4_Click" Text="Hide image" /></div>
    <div class="loglabel"><asp:Label ID="Label3" runat="server" Text="Second image upload"></asp:Label></div>
    <div class="loglabel"><asp:FileUpload ID="selectprevimg" runat="server" /></div>
    
    <div class="loglabel"><asp:Label ID="Label2" runat="server" Text="Alternate text: " AssociatedControlID="setalttextprevimg1"></asp:Label><asp:TextBox ID="setalttextprevimg1" runat="server"></asp:TextBox></div>
    <div class="loginbutton"><asp:Button ID="previmg1_btn" runat="server" OnClick="previmg1_btn_Click" Text="Confirm" /></div>
    <div class="lit"><asp:Literal ID="previmg_uploadlit" runat="server"></asp:Literal></div>
    <asp:GridView ID="GridView2" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" DataSourceID="previmg1" DataKeyNames="prevImg1">
        <Columns>
            <asp:BoundField DataField="prevImg1" HeaderText="Image ID" InsertVisible="False" ReadOnly="True" SortExpression="prevImg1" />
            <asp:BoundField DataField="width1" HeaderText="Image width" SortExpression="width1" />
            <asp:BoundField DataField="height" HeaderText="Image height" SortExpression="height" />
            <asp:BoundField DataField="altText1" HeaderText="Alternate text" SortExpression="altText1" />
            <asp:BoundField DataField="extension1" HeaderText="Image type" SortExpression="extension1" />
            <asp:BoundField DataField="prevImg3Name" HeaderText="Image name" SortExpression="prevImg3Name" />
        </Columns>
    </asp:GridView>
         <asp:SqlDataSource ID="previmg1" runat="server" ConnectionString="<%$ ConnectionStrings:db_1624956_kstardbprevimg1 %>" SelectCommand="SELECT * FROM [prevImage1_table] WHERE ([prevImg3Name] = @prevImg3Name)" DeleteCommand="DELETE FROM [prevImage1_table] WHERE [prevImg1] = @prevImg1" InsertCommand="INSERT INTO [prevImage1_table] ([width1], [height], [altText1], [extension1], [prevImg3Name]) VALUES (@width1, @height, @altText1, @extension1, @prevImg3Name)" UpdateCommand="UPDATE [prevImage1_table] SET [width1] = @width1, [height] = @height, [altText1] = @altText1, [extension1] = @extension1, [prevImg3Name] = @prevImg3Name WHERE [prevImg1] = @prevImg1">
             <DeleteParameters>
                 <asp:Parameter Name="prevImg1" Type="Int32" />
             </DeleteParameters>
             <InsertParameters>
                 <asp:Parameter Name="width1" Type="Int32" />
                 <asp:Parameter Name="height" Type="Int32" />
                 <asp:Parameter Name="altText1" Type="String" />
                 <asp:Parameter Name="extension1" Type="String" />
                 <asp:Parameter Name="prevImg3Name" Type="String" />
             </InsertParameters>
             <SelectParameters>
                 <asp:QueryStringParameter Name="prevImg3Name" QueryStringField="prod_name" Type="String" />
             </SelectParameters>
             <UpdateParameters>
                 <asp:Parameter Name="width1" Type="Int32" />
                 <asp:Parameter Name="height" Type="Int32" />
                 <asp:Parameter Name="altText1" Type="String" />
                 <asp:Parameter Name="extension1" Type="String" />
                 <asp:Parameter Name="prevImg3Name" Type="String" />
                 <asp:Parameter Name="prevImg1" Type="Int32" />
             </UpdateParameters>
        </asp:SqlDataSource>
         </div>
    <div class="imguploadheader"><asp:Label ID="Label9" runat="server" Text="3rd preview Image"></asp:Label></div>
    <div class="upimgwrap">
    <div class="imguploadmargin"><asp:Image ID="Image2" runat="server" Width="300px" Height="300px" /></div>
    <div class="regbuttoncss"><asp:Button ID="Button2" runat="server" OnClick="Button2_Click" Text="Show current image" /><asp:Button ID="Button5" runat="server" OnClick="Button5_Click" Text="Hide image" /></div>
    <div class="loglabel"><asp:FileUpload ID="selectprevimg2" runat="server" /></div>
    <div class="loglabel"><asp:Label ID="Label6" runat="server" Text="Alternate text: " AssociatedControlID="setalttextprevimg2"></asp:Label><asp:TextBox ID="setalttextprevimg2" runat="server"></asp:TextBox></div>
        <div class="loginbutton"><asp:Button ID="previmg2_btn" runat="server" Text="Confirm" OnClick="previmg2_btn_Click" /></div>
    <div><asp:Literal ID="previmg2_uploadlit" runat="server"></asp:Literal></div>
    <asp:GridView ID="GridView3" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" DataKeyNames="prevImg2" DataSourceID="previmg2">
        <Columns>
            <asp:BoundField DataField="prevImg2" HeaderText="Image ID" SortExpression="prevImg2" InsertVisible="False" ReadOnly="True" />
            <asp:BoundField DataField="width2" HeaderText="Image width" SortExpression="width2" />
            <asp:BoundField DataField="height2" HeaderText="Image height" SortExpression="height2" />
            <asp:BoundField DataField="altText2" HeaderText="Alternate text" SortExpression="altText2" />
            <asp:BoundField DataField="extension" HeaderText="Image type" SortExpression="extension" />
            <asp:BoundField DataField="prevImg2Name" HeaderText="Image name" SortExpression="prevImg2Name" />
        </Columns>
    </asp:GridView>
        <asp:SqlDataSource ID="previmg2" runat="server" ConnectionString="<%$ ConnectionStrings:db_1624956_kstardbprevImg2 %>" SelectCommand="SELECT * FROM [prevImage2_table] WHERE ([prevImg2Name] = @prevImg2Name)" DeleteCommand="DELETE FROM [prevImage2_table] WHERE [prevImg2] = @prevImg2" InsertCommand="INSERT INTO [prevImage2_table] ([width2], [height2], [altText2], [extension], [prevImg2Name]) VALUES (@width2, @height2, @altText2, @extension, @prevImg2Name)" UpdateCommand="UPDATE [prevImage2_table] SET [width2] = @width2, [height2] = @height2, [altText2] = @altText2, [extension] = @extension, [prevImg2Name] = @prevImg2Name WHERE [prevImg2] = @prevImg2">
            <DeleteParameters>
                <asp:Parameter Name="prevImg2" Type="Int32" />
            </DeleteParameters>
            <InsertParameters>
                <asp:Parameter Name="width2" Type="Int32" />
                <asp:Parameter Name="height2" Type="Int32" />
                <asp:Parameter Name="altText2" Type="String" />
                <asp:Parameter Name="extension" Type="String" />
                <asp:Parameter Name="prevImg2Name" Type="String" />
            </InsertParameters>
            <SelectParameters>
                <asp:QueryStringParameter Name="prevImg2Name" QueryStringField="prod_name" Type="String" />
            </SelectParameters>
            <UpdateParameters>
                <asp:Parameter Name="width2" Type="Int32" />
                <asp:Parameter Name="height2" Type="Int32" />
                <asp:Parameter Name="altText2" Type="String" />
                <asp:Parameter Name="extension" Type="String" />
                <asp:Parameter Name="prevImg2Name" Type="String" />
                <asp:Parameter Name="prevImg2" Type="Int32" />
            </UpdateParameters>
        </asp:SqlDataSource>
    </div>
</asp:Content>
